language: go

go:
 - master

 addons:
  apt:
    packages:
    - build-essential
    - cmake
    - pkg-config

before_install:
  - ./travis_build_opencv.sh
  # - export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):$HOME/usr/lib/pkgconfig
  # - export INCLUDE_PATH=$HOME/usr/include:${INCLUDE_PATH}
  # - export LD_LIBRARY_PATH=$HOME/usr/lib:${LD_LIBRARY_PATH}
  # - sudo ln /dev/null /dev/raw1394
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start

install:
  # Install all external dependencies, ensuring they are updated.
  - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v golang-samples)

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
